export type DateDifferenceLocale = "ko" | "en";

export const dateDifferenceContent = {
  ko: {
    title: "날짜 차이 계산기",
    description:
      "두 날짜 사이의 총 일수, 주 단위 기간과 달력 기준 연·월·일 차이를 계산합니다.",
    category: "사업·생활",
    input: "날짜 입력",
    startDate: "시작일",
    endDate: "종료일",
    calculate: "날짜 차이 계산하기",
    reset: "초기화",
    result: "계산 결과",
    totalDays: "총 날짜 차이",
    weeks: "주 단위 기간",
    calendarBreakdown: "달력 기준 기간",
    direction: "날짜 순서",
    daysUnit: "일",
    weeksUnit: "주",
    yearsUnit: "년",
    monthsUnit: "개월",
    forward: "종료일이 시작일 이후",
    reverse: "종료일이 시작일 이전",
    same: "같은 날짜",
    error: "시작일과 종료일에 올바른 날짜를 입력하세요.",
    note: "총 일수는 두 달력 날짜의 실제 차이입니다. 연·월·일 표시는 더 이른 날짜에서 더 늦은 날짜까지 달력 기준으로 분해한 기간입니다.",
    method:
      "두 날짜를 UTC 달력 날짜로 정규화해 총 일수 차이를 계산합니다. 이후 더 이른 날짜에서 더 늦은 날짜까지 완전한 연, 완전한 개월, 남은 일수 순으로 달력 기간을 분해합니다.",
    tips: "계약 기간, 여행 일정, 프로젝트 기간처럼 두 날짜 사이의 길이를 비교할 때 사용하세요. 특정 목표일까지 D-·D+ 카운트다운이 필요하면 디데이 계산기가 더 적합합니다.",
    metaTitle: "날짜 차이 계산기 | 두 날짜 사이 일수·기간 계산",
  },
  en: {
    title: "Date Difference Calculator",
    description:
      "Calculate total days, week breakdown, and calendar years, months, and days between two dates.",
    category: "Business & Everyday",
    input: "Date inputs",
    startDate: "Start date",
    endDate: "End date",
    calculate: "Calculate date difference",
    reset: "Reset",
    result: "Results",
    totalDays: "Total date difference",
    weeks: "Week breakdown",
    calendarBreakdown: "Calendar duration",
    direction: "Date order",
    daysUnit: "days",
    weeksUnit: "weeks",
    yearsUnit: "years",
    monthsUnit: "months",
    forward: "End date is after start date",
    reverse: "End date is before start date",
    same: "Same date",
    error: "Enter valid start and end dates.",
    note: "Total days is the exact calendar-day gap. The years, months, and days result breaks the absolute interval into calendar units from the earlier date to the later date.",
    method:
      "Both inputs are normalized as UTC calendar dates for the total-day difference. The calculator then walks from the earlier date to the later date using complete years, complete months, and remaining days.",
    tips: "Use this for contracts, trips, projects, and any interval between two dates. For a target-date D-/D+ countdown, use the D-Day Calculator instead.",
    metaTitle: "Date Difference Calculator | Days Between Dates",
  },
} satisfies Record<DateDifferenceLocale, Record<string, string>>;
