export type JeonseVsRentLocale = "ko" | "en";

export const jeonseVsRentContent = {
  ko: {
    title: "전세 보증금 vs 월세 비용 비교 계산기",
    description:
      "전세대출 이자, 보증금에 묶이는 자기자금의 기회비용, 월세 보증금 기회비용과 월세 납부액을 같은 기간으로 비교합니다.",
    category: "부동산·주거",
    input: "비교 조건",
    jeonseDeposit: "전세 보증금",
    jeonseLoanAmount: "전세대출 금액",
    jeonseLoanRate: "전세대출 연이율",
    monthlyRentDeposit: "월세 보증금",
    monthlyRent: "월세",
    opportunityRate: "자기자금 연 기회수익률",
    comparisonMonths: "비교 기간",
    calculate: "비용 비교하기",
    reset: "초기화",
    result: "비용 비교 결과",
    jeonseCost: "전세 총 경제적 비용",
    rentCost: "월세 총 경제적 비용",
    difference: "월세 비용 - 전세 비용",
    cheaperOption: "더 저렴한 선택",
    jeonse: "전세",
    rent: "월세",
    equal: "비용 동일",
    breakEvenRent: "전세와 같아지는 월세",
    jeonseInterest: "전세대출 이자",
    jeonseOpportunity: "전세 자기자금 기회비용",
    rentPayments: "기간 중 월세 납부액",
    rentDepositOpportunity: "월세 보증금 기회비용",
    error:
      "금액·금리는 0 이상, 비교 기간은 1개월 이상으로 입력하고 전세대출은 전세 보증금을 넘지 않게 입력해 주세요.",
    note: "보증금 원금 자체는 계약 종료 시 돌려받는다고 가정해 비용에 포함하지 않고, 보증금에 묶인 자기자금의 기회비용과 대출이자만 비교합니다. 중개보수, 이사비, 세금, 보증금 미반환 위험, 대출 원금상환 방식은 포함하지 않습니다.",
    method:
      "전세는 전세대출 이자와 전세 보증금 중 자기자금에 대한 복리 기회비용을 합산합니다. 월세는 월세 보증금의 기회비용과 비교 기간 동안의 월세 납부액을 합산합니다. 두 경제적 비용을 같은 기간으로 비교합니다.",
    tips: "기회수익률은 보증금에 묶이지 않았다면 기대할 수 있는 연 수익률 가정입니다. 확정 수익률이 아니므로 보수적·중립·공격적 값을 바꿔 결과 민감도를 확인하세요.",
    metaTitle: "전세 vs 월세 비용 비교 계산기 | 보증금·이자·기회비용",
  },
  en: {
    title: "Jeonse Deposit vs Monthly Rent Cost Calculator",
    description:
      "Compare jeonse loan interest and deposit opportunity cost with monthly-rent payments and deposit opportunity cost over the same period.",
    category: "Housing & Real Estate",
    input: "Comparison assumptions",
    jeonseDeposit: "Jeonse deposit",
    jeonseLoanAmount: "Jeonse loan amount",
    jeonseLoanRate: "Jeonse loan annual rate",
    monthlyRentDeposit: "Monthly-rent deposit",
    monthlyRent: "Monthly rent",
    opportunityRate: "Annual opportunity return on your own cash",
    comparisonMonths: "Comparison period",
    calculate: "Compare costs",
    reset: "Reset",
    result: "Cost comparison",
    jeonseCost: "Total jeonse economic cost",
    rentCost: "Total monthly-rent economic cost",
    difference: "Rent cost - jeonse cost",
    cheaperOption: "Lower-cost option",
    jeonse: "Jeonse",
    rent: "Monthly rent",
    equal: "Equal cost",
    breakEvenRent: "Break-even monthly rent",
    jeonseInterest: "Jeonse loan interest",
    jeonseOpportunity: "Jeonse equity opportunity cost",
    rentPayments: "Rent payments over period",
    rentDepositOpportunity: "Rent-deposit opportunity cost",
    error:
      "Enter non-negative amounts and rates, a comparison period of at least one month, and a jeonse loan no larger than the jeonse deposit.",
    note: "This South Korea housing comparison assumes refundable deposits are returned at the end of the lease, so deposit principal itself is not treated as a cost. It compares financing and opportunity costs only and excludes brokerage, moving costs, taxes, deposit-return risk, and loan-principal amortization.",
    method:
      "Jeonse cost combines jeonse-loan interest with compounded opportunity cost on the part of the jeonse deposit funded by your own cash. Monthly-rent cost combines the opportunity cost of the rent deposit with all rent payments over the selected period.",
    tips: "The opportunity return is an assumption for what your tied-up cash might otherwise earn, not a guaranteed return. Try conservative and higher-return scenarios to see how sensitive the decision is.",
    metaTitle: "Jeonse vs Monthly Rent Cost Calculator | Deposit & Interest Comparison",
  },
} satisfies Record<JeonseVsRentLocale, Record<string, string>>;
