export const englishCalculatorDescriptions: Readonly<Record<string, string>> = {
  "weekly-holiday-pay": "Estimate weekly holiday pay from hours and wages.",
  "severance-pay": "Estimate statutory severance pay.",
  "unemployment-benefits": "Estimate unemployment benefit payments.",
  "net-salary": "Estimate take-home salary after deductions.",
  "hourly-wage": "Convert pay and work time to an hourly wage.",
  "social-insurance": "Estimate social insurance contributions.",
  "average-wage": "Calculate average wage for a period.",
  "salary-raise": "Compare current and proposed salary.",
  "salary-conversion": "Convert pay across salary periods.",
  "overtime-pay": "Estimate overtime compensation.",
  "night-work-pay": "Estimate night-work compensation.",
  "holiday-work-pay": "Estimate holiday-work compensation.",
  "minimum-wage": "Check pay against minimum-wage rules.",
  "annual-leave-allowance": "Estimate unused leave allowance.",
  "retirement-pension": "Estimate retirement pension value.",
  "gross-up-salary": "Find gross salary for a target net amount.",
  "part-time-monthly-pay": "Estimate monthly part-time pay.",
  "daily-worker-pay": "Estimate daily-worker pay.",
  "work-hours-converter": "Convert daily, weekly, and monthly work hours.",
  "total-compensation-comparison": "Compare total compensation across offers.",
  "salary-negotiation-target": "Set a salary negotiation target.",
  "parental-leave-benefit": "Estimate parental-leave benefits.",
  "maternity-leave-benefit": "Estimate maternity-leave benefits.",
  ltv: "Calculate the loan-to-value ratio.",
  dsr: "Estimate the debt service ratio.",
  "stress-dsr": "Estimate debt service under a stress rate.",
  "mortgage-loan-limit": "Estimate a mortgage borrowing limit.",
  loan: "Calculate loan payments and total interest.",
  "loan-interest-comparison": "Compare interest costs across loans.",
  "loan-refinancing-savings": "Estimate savings from refinancing.",
  "balloon-payment": "Calculate payments with a balloon balance.",
  "mortgage-payment": "Estimate recurring mortgage payments.",
  "jeonse-loan-interest": "Estimate interest on a jeonse loan.",
  "credit-loan-interest": "Estimate unsecured loan interest.",
  "early-loan-repayment-fee": "Estimate an early repayment fee.",
  dti: "Calculate the debt-to-income ratio.",
  "loan-affordability": "Estimate an affordable loan amount.",
  "debt-repayment-period": "Estimate time needed to repay debt.",
  "credit-card-installment-interest": "Estimate card installment interest.",
  "jeonse-loan-limit": "Estimate a jeonse borrowing limit.",
  "real-estate-acquisition-tax": "Estimate real-estate acquisition tax.",
  "capital-gains-tax": "Estimate capital gains tax.",
  "gift-tax": "Estimate gift tax.",
  "inheritance-tax": "Estimate inheritance tax.",
  "property-tax": "Estimate property tax.",
  "comprehensive-real-estate-holding-tax": "Estimate holding tax.",
  "value-added-tax": "Calculate value added tax.",
  "comprehensive-income-tax": "Estimate comprehensive income tax.",
  "withholding-tax": "Estimate withholding tax.",
  "freelancer-3-3-tax": "Estimate freelancer withholding tax.",
  "year-end-tax-refund": "Estimate year-end tax settlement.",
  "retirement-income-tax": "Estimate retirement income tax.",
  "earned-income-withholding-tax": "Estimate earned-income withholding.",
  "rent-conversion-rate": "Calculate deposit-to-rent conversion rate.",
  "jeonse-monthly-rent-conversion": "Convert jeonse deposits and monthly rent.",
  "real-estate-brokerage-fee": "Estimate real-estate brokerage fees.",
  "rent-affordability": "Estimate an affordable rent budget.",
  "jeonse-vs-rent": "Compare jeonse and monthly-rent costs.",
  "home-purchase-total-cost": "Estimate total home-purchase cost.",
  "home-sale-net-proceeds": "Estimate net proceeds from a home sale.",
  "rental-yield": "Calculate gross and net rental yield.",
  "apartment-management-fee-budget": "Estimate apartment management fees.",
  deposit: "Calculate deposit interest and maturity value.",
  savings: "Project recurring savings growth.",
  "compound-interest": "Project growth with compound interest.",
  "savings-goal": "Find contributions for a savings goal.",
  "inflation-purchasing-power": "Estimate inflation and purchasing power.",
  "pension-savings-tax-credit": "Estimate a pension-savings tax credit.",
  "retirement-pension-tax-credit": "Estimate a retirement-pension tax credit.",
  "emergency-fund": "Estimate an emergency-fund target.",
  "fire-retirement-target": "Estimate a FIRE retirement target.",
  "retirement-withdrawal": "Estimate sustainable retirement withdrawals.",
  "pension-future-monthly-income": "Project future monthly pension income.",
  "apr-apy-conversion": "Convert between APR and APY.",
  cagr: "Calculate compound annual growth rate.",
  "stock-average-cost": "Calculate weighted average stock cost.",
  "stock-profit-loss": "Calculate stock profit, loss, and return.",
  dividend: "Estimate dividend income.",
  "dividend-yield": "Calculate dividend yield.",
  "dollar-cost-averaging": "Project recurring investment growth.",
  "investment-fee-impact": "Compare investment outcomes after fees.",
  "isa-tax-savings": "Estimate ISA tax savings.",
  "dividend-reinvestment": "Project growth with reinvested dividends.",
  "portfolio-rebalancing": "Calculate trades to restore target weights.",
  "bond-yield-to-maturity": "Estimate a bond's yield to maturity.",
  "bond-price": "Estimate a bond price from yield and cash flows.",
  "crypto-average-cost": "Calculate weighted average crypto cost.",
  "crypto-profit-loss": "Calculate crypto profit, loss, and return.",
  "staking-reward": "Estimate staking rewards.",
  "foreign-currency-average-cost": "Calculate average foreign-currency cost.",
  "currency-conversion": "Convert currencies with an exchange rate.",
  "employer-total-labor-cost": "Estimate total employer labor cost.",
  percentage: "Calculate percentages and percentage change.",
  "discount-sale-price": "Calculate sale price after a discount.",
  age: "Calculate age from a birth date.",
  "d-day": "Count days to or from a target date.",
  "date-difference": "Calculate elapsed time between dates.",
  "break-even-sales": "Calculate break-even units and revenue.",
  "operating-profit": "Calculate operating profit and margin.",
  "business-cash-runway": "Estimate cash burn and business runway.",
};

export function getEnglishCalculatorDescription(id: string) {
  const description = englishCalculatorDescriptions[id];
  if (!description) {
    throw new Error(`Unknown English calculator description for: ${id}`);
  }
  return description;
}
