export type RentalYieldLocale = "ko" | "en";

export const rentalYieldContent = {
  ko: {
    title: "임대수익률 계산기",
    description: "매입가, 월 임대료, 공실률과 연간 운영비를 반영해 임대 부동산의 총수익률과 순수익률을 계산합니다.",
    category: "부동산·주거",
    input: "임대수익 입력",
    purchasePrice: "부동산 매입가",
    monthlyRent: "월 임대료",
    annualOtherIncome: "연간 기타 임대수입",
    annualOperatingCosts: "연간 운영비",
    vacancyRatePercent: "예상 공실률 (%)",
    calculate: "수익률 계산하기",
    reset: "초기화",
    result: "예상 임대수익률",
    grossAnnualIncome: "연간 총 임대수입",
    effectiveAnnualIncome: "공실 반영 유효수입",
    netOperatingIncome: "순영업소득(NOI)",
    grossYieldPercent: "총 임대수익률",
    netYieldPercent: "순 임대수익률",
    error: "매입가는 0보다 크게, 금액은 0 이상, 공실률은 0~100%로 입력해 주세요.",
    note: "순수익률은 금융비용·소득세·양도세·자본차익을 제외한 단순 운영수익률입니다. 실제 투자 판단에는 대출조건, 세금, 수선충당, 거래비용을 별도로 반영하세요.",
    method: "연간 총 임대수입은 월 임대료×12와 기타수입의 합입니다. 공실률을 차감한 유효수입에서 연간 운영비를 빼 순영업소득(NOI)을 계산하고, 매입가 대비 총수입과 NOI 비율을 각각 총수익률과 순수익률로 표시합니다.",
    tips: "관리비, 재산세, 보험, 유지보수, 수선비 등 실제 소유자가 부담하는 반복 비용을 운영비에 포함하고, 지역과 물건에 맞는 현실적인 공실률을 사용하세요.",
    metaTitle: "임대수익률 계산기 | 총수익률·순수익률·NOI",
  },
  en: {
    title: "Rental Yield Calculator",
    description: "Estimate gross and net rental yield from purchase price, monthly rent, vacancy, other income, and annual operating costs.",
    category: "Housing & Real Estate",
    input: "Rental yield inputs",
    purchasePrice: "Property purchase price",
    monthlyRent: "Monthly rent",
    annualOtherIncome: "Annual other rental income",
    annualOperatingCosts: "Annual operating costs",
    vacancyRatePercent: "Expected vacancy rate (%)",
    calculate: "Calculate rental yield",
    reset: "Reset",
    result: "Estimated rental yield",
    grossAnnualIncome: "Gross annual rental income",
    effectiveAnnualIncome: "Effective income after vacancy",
    netOperatingIncome: "Net operating income (NOI)",
    grossYieldPercent: "Gross rental yield",
    netYieldPercent: "Net rental yield",
    error: "Enter a purchase price above zero, non-negative amounts, and a vacancy rate from 0% to 100%.",
    note: "Net yield here is a simple operating yield before financing costs, income tax, capital-gains tax, and appreciation. Add your own debt, tax, reserves, and transaction-cost assumptions for a full investment analysis.",
    method: "Gross annual rental income equals monthly rent × 12 plus other rental income. Effective income applies the vacancy assumption. Net operating income subtracts annual operating costs. Gross and net yields divide gross income and NOI by purchase price.",
    tips: "Include owner-paid recurring costs such as management, property tax, insurance, maintenance and repairs, and use a vacancy assumption appropriate to the property and market.",
    metaTitle: "Rental Yield Calculator | Gross Yield, Net Yield & NOI",
  },
} satisfies Record<RentalYieldLocale, Record<string, string>>;
